mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

app_name='polls'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('polls.urls', namespace="polls")),
]

mysite/polls/urls.py
from django.urls import path,re_path
from . import views

app_name='polls'

urlpatterns=[
    path('',views.index,name="index"),
    path('first_page/',views.first_page,name="first_page"),
    re_path(r'^(?P<question_id>[0-9]+)/details/$', views.details, name='details'),
    re_path(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    re_path(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    Question_text=models.CharField(max_length=200)
    answer=models.CharField(max_length=200,default='No answer suggested')
    pub_date=models.DateTimeField('date Published')
    def __str__(self):
        return self.Question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    choice_text=models.CharField(max_length=200)
    #votes=models.CharField(max_length=200)
    Question=models.ForeignKey(Question,on_delete=models.CASCADE)
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import Question,Choice
from django.urls import reverse
from django.http import Http404


# Create your views here.

def index(request):
    return render(request, 'polls/index.html')

def first_page(request):
    latest_questions=Question.objects.order_by('-pub_date')[:5]
    template=loader.get_template('polls/first_page.html')
    response=template.render({'latest_questions':latest_questions})
    return HttpResponse(response)

def details(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exit")
    template=loader.get_template('polls/details.html')
    response=template.render({'question':question})
    return HttpResponse(response)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question,}) 

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.answer
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'polls/css/details.css' %}">
    <link rel="stylesheet" href="{% static 'polls/css/index.css' %}">
    <title>Document</title>
</head>
<body>
    {% block main_content %}
    {% endblock %}
</body>
</html>

mysite/polls/templates/polls/details.html
{% extends 'polls/base.html' %}

{% block main_content %}


    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="csrf-token" value="CIwNZNlR4XbisJF39I8yWnWX9wX4WFoz" />

        <div class="container-fluid">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2>{{question.Question_text}}</h2>
                    </div>
                    {% if error_message %} <p><strong>{{error_message}}</strong></p>{% endif %}
                    <div class="modal-body">
                        <div class="col-xs-3 5"> </div>
                        <div class="quiz" id="quiz" data-toggle="buttons"> 
                            {% for Choice in question.choice_set.all %}
                                <label class="element-animation1 btn btn-lg btn-danger btn-block"><span class="btn-label">
                                <i class="glyphicon glyphicon-chevron-right"></i></span> 
                                <input type="radio" name="Choice" id="Choice{{forloop.counter}}" class="text-style" value="{{Choice.id}}">{{Choice.choice_text}}</label> 
                            {% endfor %}
                        </div>
                        <br><br><br>
                        <center><button type="submit" class="btn btn-danger size">Vote</button></center>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </form>

{% endblock %}

mysite/polls/templates/polls/first_page.html
{% extends 'polls/base.html' %}

{% block main_content %}
    {% if latest_questions %}
        <ul>
            {% for Question in latest_questions %}
                <li><a href="{% url 'polls:details' Question.id %}"><b>{{ Question.Question_text }}</b></a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You don't have any question.</p>
    {% endif %}
    
{% endblock %}

mysite/polls/templates/polls/footer.html
<hr>
<p>footer</p>
</hr>

mysite/polls/templates/polls/header.html
<center><h1>Welcome to Question Series</h1></center>

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block main_content %}
<h1 class="heading">Welcome to the Question series</h1>
<div class="start">
    <a href="first_page/" id="anchor">Let's start!</a>
</div>

{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1>{{question.Question_text}}</h1>
<h2 style="color: #ffebcd;">{{question.answer}}</h2>
<a href="{% url 'polls:index' %}">Go to the questions page again!</a>
    

{% endblock %}